version: '3.9'
services:
  delivery-service:
    container_name: delivery-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:8080
    networks:
      - backend

networks:
  backend:
    name: kafka-network
    external: true